language: ruby

cache:
  - gem
  - npm

before_install:
  - nvm install 9

install:
  - bundle install
  - npm install

script:
  - npm run build
  - jekyll build

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: mattmatters.io
  skip_cleanup: true
  local_dir: _site
  cache_control: "max-age=21600"
