# Site settings
title: Matt Matters
description: "Matters that effect mostly Matt"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://mattmatters.github.io"
# User settings
username: Matt Lewis
user_title: Web Everything
email: domattthings@gmail.com
twitter_username: dancinpolkabear
github_username:  mattmatters
gitlab_username: mattmatters
profile_picture: /assets/img/coolMatt.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: Elair
    url: https://github.com/mattmatters/elair
  - name: This site
    url: https://github.com/mattmatters/mattmatters.github.io
  - name: Kinda Small URL
    url: http://www.kindasmallurl.fun

random:
  - name: Muffin Madness
    url: http://muffinmadness.win
    description: "The breadth of muffins"
  - name: Vanity Site
    url: http://themattersofmatt.com
    description: "Look at this when in need of a confidence boost"
  - name: Duck Dynasty 2
    url: http://duckdynasty2.site/
    description: "Commission for the upcoming sequel."
  - name: Another Calculator
    url: http://calc-redux.com.s3-website-us-east-1.amazonaws.com/
    description: "Calculator written using the new and hip React-Redux"
  - name: Barlen Electronics
    url: http://barlenelectronics.com
    description: "Commissioned company website"
  - name: Straw Brian Short Cake
    url: http://strawbrianshortcake.com/
    description: "My <b>finest</b> graphic design work ever."
  - name: B Nice B Short
    url: http://bnicebshort.com.s3-website-us-east-1.amazonaws.com
    description: "My <b>worst</b> graphic design work ever."
  - name: Markdown Previewer
    url: http://markdownpreview.com.s3-website-us-east-1.amazonaws.com
    description: "Everyone makes one of these"
  - name: Old bootsrap thing I found on a hardrive
    url: http://loureedtribute.com.s3-website-us-east-1.amazonaws.com
    description: "I think I made this a long time ago."
  - name: I have no idea
    url: http://photocrossfadetest.com.s3-website-us-east-1.amazonaws.com
    description: "The world can have this too."

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
